# Generated by Django 3.2.9 on 2021-11-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todolist',
            options={},
        ),
        migrations.AlterField(
            model_name='todolist',
            name='category',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
